import { Footer } from '@/layout/Footer';
import { Header } from '@/layout/Header';
import '@/styles/globals.css';
import { LayoutComponent } from '@/types/next.types';
import { cn } from '@/utils/cn.util';
import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
const montserrat = Montserrat({ subsets: ['cyrillic'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const RootLayout: LayoutComponent = async ({ children }) => {
	return (
		<html lang="ru">
			<head>
				<meta name="description" content={''} />
				<meta name="theme-color" content="#FFC000" />
				<link rel="icon" href="/favicon.ico" />
			</head>
			<body className={cn(montserrat.className, 'scroll-smooth antialiased')}>
				<Header />
				<main>{children}</main>
				<Footer />
			</body>
		</html>
	);
};

export default RootLayout;
